version: '3'
services:
  mqtt:
    image: eclipse-mosquitto:2.0-openssl
    volumes:
      - ./mounted-volumes/mqtt/config:/mosquitto/config
      - ./mounted-volumes/mqtt/data:/mosquitto/data
    ports:
      - "8883:8883"
